=== AdminBit/Dami1Archive/LMS/XML/path/correction.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="exam">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="titre" type="xs:string" />
				<xs:element name="date">
					<xs:complexType>
						<xs:attribute name="mois" use="required" />
						<xs:attribute name="annee" type="xs:integer" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="questions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="question" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="partie" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="code" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AdminBit/Dami1Archive/LMS/XML/path/tp1.xml
<?xml version = "1.0" encoding="UTF-8" standalone="yes"?>

<exam xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
      xsd:noNamespaceSchemaLocation="correction.xsd"
      code="coursXML">
	<titre>Outils et Doc XML</titre>
	<date mois="enero" annee="2008"/>
		<questions>
			<question>
				<partie/>
			</question>	
			<question>
				<partie/>
			</question>	
			<question>
				<partie/>
			</question>	
			<question>
				<partie/>
			</question>	
			<question>
				<partie/>
			</question>	
		</questions>
</exam>
